name: CI
on:
  workflow_dispatch:
  push:

jobs:
  #
  # basic tests, running on the raw machine with "default" settings
  #
  linux-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install oclgrind gcc ocl-icd-opencl-dev intel-opencl-icd golang -y
      - name: Unit tests (no vgpu)
        run: source contrib/env.sh && eyot_test
      - name: Unit tests (oclgrind)
        run: source contrib/env.sh && eyot_test
        env:
          EyotTestOclGrind: y
  mac-basic:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: brew install go
      - run: source contrib/env.sh && eyot_test

  #
  # Nix tests, which are more thorough
  #
  nix-tests:
    strategy:
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    needs:
    - mac-basic
    - linux-basic
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake check -L
      - run: echo "cpu fn main() { print_ln(true) }" > test.ey
      - run: nix run . -- run test.ey
      - run: nix develop -i -c "eyot" "run" "tests/helloworld.ey"

  #
  # Various checks, and artefact builds
  #

  # Check consumption of nix flake in example
  nix-example-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
    - nix-tests
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Check nix flake example
        working-directory: ${{runner.workspace}}/eyot/examples/consume-flake
        run: nix build . && ./result/bin/out.exe

  # Build artefacts
  build-artefacts:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    needs:
    - nix-tests
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      # .deb package
      - run: nix build .#deb
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ./result/eyot.deb
          overwrite: true
          retention-days: 1

      # playground .deb package
      - run: nix build .#playground
      - uses: actions/upload-artifact@v4
        with:
          name: playground
          path: ./result/eyot-playground.deb
          overwrite: true
          retention-days: 1

      # documentation
      - name: Generate docs
        run: nix build .#docs
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/

  # Check the .deb installs and works on a clean machine
  check-deb:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    needs:
    - build-artefacts
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: deb
        path: ./eyot.deb
    - run: echo "cpu fn main() { print_ln(true) }" > test.ey
    - run: sudo apt install --reinstall --yes ./eyot.deb
    - run: eyot run test.ey
    - run: man eyot

  #
  # Deploy site and playground
  #
  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
    - check-deb
    - nix-example-test
    - build-artefacts
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
  deploy-playground:
    runs-on: ubuntu-latest
    needs:
    - check-deb
    - nix-example-test
    - build-artefacts
    steps:
      # ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFbuHFjiWNhfOsUJfmSIIeYS3AVb+i1OZauxpm31GUoeMGfCIk1OIiIBBk8NcRXpgQ22iHmweuAAreDoU5XstDo= gha
    - name: Prep ssh
      run: |-
        echo "${{ secrets.PlaygroundServerKey }}" > /home/runner/sshkey
        chmod 0600 /home/runner/sshkey
        mkdir -p ~/.ssh 
        ssh-keyscan eyot-playground.cowleyforniastudios.com > /home/runner/.ssh/known_hosts
    - uses: actions/download-artifact@v8
      with:
        name: playground
        path: ./eyot-playground.deb
    - run: ssh -i /home/runner/sshkey root@eyot-playground.cowleyforniastudios.com "sudo apt remove eyot-playground -y || true"
    - run: scp -i /home/runner/sshkey ./eyot-playground.deb root@eyot-playground.cowleyforniastudios.com:~/
    - run: ssh -i /home/runner/sshkey root@eyot-playground.cowleyforniastudios.com "sudo apt install ~/eyot-playground.deb -y"
    - run: ssh -i /home/runner/sshkey root@eyot-playground.cowleyforniastudios.com "sudo systemctl restart eyot-playground"


