name: Eyot Tests
on:
  workflow_dispatch:
  push:

jobs:
  # unit tests running on "raw" machine
  host-tests:
    strategy:
      matrix:
        os:
          # intel mac
          - "macos-13"
          # aarch mac
          - "macos-15"
          # intel linux
          - "ubuntu-24.04"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: brew install go
        if: contains(matrix.os, 'macos')
      - run: sudo apt install gcc ocl-icd-opencl-dev intel-opencl-icd golang -y
        if: contains(matrix.os, 'ubuntu')
      - name: Unit tests
        run: source contrib/env.sh && eyot_test

  # nix flake checks
  nix-tests:
    strategy:
      matrix:
        os:
          # intel mac
          - "macos-13"
          # aarch mac
          - "macos-15"
          # intel linux
          - "ubuntu-24.04"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      # unit tests
      - run: nix flake check -L
        name: Run all builds and tests

      # minimal hello world
      - run: echo "cpu fn main() { print_ln(true) }" > test.ey
        name: Create an example program

      # install and run the deb package (on linux)
      - run: nix build .#deb
        name: Build the debian package
        if: contains(matrix.os, 'ubuntu')
      - run: sudo apt install --reinstall --yes ./result/eyot.deb
        name: Install debian package
        if: contains(matrix.os, 'ubuntu')
      - run: eyot run test.ey
        name: Run eyot via the debian package
        if: contains(matrix.os, 'ubuntu')

      # check running via nix ok
      - run: nix run . -- run test.ey
        name: Run eyot from the flake

      # run a command within the nix shell to ensure that is ok
      - run: nix develop -i -c "eyot" "run" "tests/helloworld.ey"
        name: Check the nix shell
